### ISSUE TITLE
Error when right click on object and selecting "Expand property set"

### ISSUE THREAD

**Issue by balrobs** [yorikvanhavre/FreeCAD-NativeIFC#45]
After importing the [IFC Schependomlaan.ifc](https://github.com/buildingSMART/Sample-Test-Files/blob/master/IFC%202x3/Schependomlaan/Design%20model%20IFC/IFC%20Schependomlaan.ifc) file and selecting "Expand property set" with a right click at an object (i.e. dakpan (vlak)005) I see this error:
```
09:15:10  Traceback (most recent call last):
09:15:10    File "C:\Users\balrobs\AppData\Roaming\FreeCAD\Mod\FreeCAD-NativeIFC\.\ifc_viewproviders.py", line 209, in showProps
09:15:10      ifc_tools.show_psets(self.Object)
09:15:10    File "C:\Users\balrobs\AppData\Roaming\FreeCAD\Mod\FreeCAD-NativeIFC\.\ifc_tools.py", line 1212, in show_psets
09:15:10      obj.addProperty("App::PropertyString", pname, gname)
09:15:10  NameError: {'sclassname': 'class Base::NameError', 'sErrMsg': "Invalid property name 'Home Story'", 'sfile': 'D:\\bld\\freecad_1684045270349\\work\\src\\App\\DynamicProperty.cpp', 'iline': 176, 'sfunction': 'class App::Property *__cdecl App::DynamicProperty::addDynamicProperty(class App::PropertyContainer &,const char *,const char *,const char *,const char *,short,bool,bool)', 'swhat': "Invalid property name 'Home Story'", 'btranslatable': False, 'breported': False}
```
![screenshot](https://github.com/yorikvanhavre/FreeCAD-NativeIFC/assets/73989799/804cac58-581b-4cca-bcc1-2bf9ac5b34e0)

**Comment by yorikvanhavre** [comment]
Ok I see the error too... I think I didn't handle property names with a space in them correctly :) Will fix that ASAP
