### ISSUE TITLE
error while adding new object

### ISSUE THREAD

**Issue by arunkvijay** [yorikvanhavre/FreeCAD-NativeIFC#46]
Hi Yorik,
I am getting error while adding new object created in freecad to ifc. the error is same while trying to add from the UI and also through python console

`06:22:44  Traceback (most recent call last):
  File "/home/arun/.local/share/FreeCAD/Mod/FreeCAD-NativeIFC/./ifc_viewproviders.py", line 246, in dropObject
    ifc_tools.aggregate(incoming_object, parent)
  File "/home/arun/.local/share/FreeCAD/Mod/FreeCAD-NativeIFC/./ifc_tools.py", line 921, in aggregate
    product = create_product(obj, parent, ifcfile)
  File "/home/arun/.local/share/FreeCAD/Mod/FreeCAD-NativeIFC/./ifc_tools.py", line 988, in create_product
    representation, placement, shapetype = exportIFC.getRepresentation(
  File "/tmp/.mount_FreeCAmo37dh/usr/Mod/Arch/exportIFC.py", line 2067, in getRepresentation
    profile = getProfile(ifcfile,pi)
  File "/tmp/.mount_FreeCAmo37dh/usr/Mod/Arch/exportIFC.py", line 1906, in getProfile
    pxvc = ifcbin.createIfcDirection(tuple(d)[:2])
<class 'NameError'>: name 'ifcbin' is not defined`

**Comment by yorikvanhavre** [comment]
Hm your version of FreeCAD is probably too old (you need a very recent version, >= v0.20.3) and you didn't see the error message in the Python console... I'll make a better message
