### ISSUE TITLE
<class 'ValueError'>: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by Mannshoch** [yorikvanhavre/FreeCAD-NativeIFC#56]
```
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.21.1.33694 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: German/Switzerland (de_CH)
Installed mods: 
  * FreeCAD-NativeIFC 2023.10.27
```
I uninstalled FreeCAD with User settings, an this FreeCAD runs a portable version in Windows
Is a different IFC file than the last times I wrote Issues.
```
10:31:43  DirectWrite: CreateFontFaceFromHDC() failed (Gibt einen Fehler in einer Eingabedatei an, zum Beispiel eine Schriftartdatei.) for QFontDef(Family="8514oem", pointsize=10, pixelsize=20, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("8514oem", lfWidth=0, lfHeight=-20) dpi=192
10:32:13  DirectWrite: CreateFontFaceFromHDC() failed (Gibt einen Fehler in einer Eingabedatei an, zum Beispiel eine Schriftartdatei.) for QFontDef(Family="8514oem", pointsize=10, pixelsize=20, styleHint=5, weight=75, stretch=100, hintingPreference=0) LOGFONT("8514oem", lfWidth=0, lfHeight=-20) dpi=192
10:33:27  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\%USERNAME%\AppData\Roaming\FreeCAD\Mod\FreeCAD-NativeIFC\.\ifc_import.py", line 48, in open
    insert(filename, doc.Name)
  File "C:\Users\%USERNAME%\AppData\Roaming\FreeCAD\Mod\FreeCAD-NativeIFC\.\ifc_import.py", line 86, in insert
    ifc_psets.load_psets(prj_obj)
  File "C:\Users\%USERNAME%\AppData\Roaming\FreeCAD\Mod\FreeCAD-NativeIFC\.\ifc_psets.py", line 232, in load_psets
    load_psets(child)
  File "C:\Users\%USERNAME%\AppData\Roaming\FreeCAD\Mod\FreeCAD-NativeIFC\.\ifc_psets.py", line 232, in load_psets
    load_psets(child)
  File "C:\Users\%USERNAME%\AppData\Roaming\FreeCAD\Mod\FreeCAD-NativeIFC\.\ifc_psets.py", line 232, in load_psets
    load_psets(child)
  [Previous line repeated 1 more time]
  File "C:\Users\%USERNAME%\AppData\Roaming\FreeCAD\Mod\FreeCAD-NativeIFC\.\ifc_psets.py", line 226, in load_psets
    show_psets(obj)
  File "C:\Users\%USERNAME%\AppData\Roaming\FreeCAD\Mod\FreeCAD-NativeIFC\.\ifc_psets.py", line 94, in show_psets
    ptype, value = pvalue.split("(", -1)
<class 'ValueError'>: too many values to unpack (expected 2)
```
follow Error flooded the log window
```
10:34:11  Traceback (most recent call last):
  File "C:\Users\%USERNAME%\AppData\Roaming\FreeCAD\Mod\FreeCAD-NativeIFC\.\ifc_objects.py", line 129, in execute
    ifc_generator.generate_geometry(obj, cached=cached)
  File "C:\Users\%USERNAME%\AppData\Roaming\FreeCAD\Mod\FreeCAD-NativeIFC\.\ifc_generator.py", line 65, in generate_geometry
    elements = get_decomposition(obj)
  File "C:\Users\%USERNAME%\AppData\Roaming\FreeCAD\Mod\FreeCAD-NativeIFC\.\ifc_generator.py", line 316, in get_decomposition
    elements = get_decomposed_elements(element, obj)
  File "C:\Users\%USERNAME%\AppData\Roaming\FreeCAD\Mod\FreeCAD-NativeIFC\.\ifc_generator.py", line 347, in get_decomposed_elements
    for child in ifcopenshell.util.element.get_decomposition(
<class 'TypeError'>: get_decomposition() got an unexpected keyword argument 'is_recursive'
```
```
10:35:09  Recompute failed!
```

**Comment by yorikvanhavre** [comment]
I think this indicates a wrong version of IfcOpenShell... Is it recent enough?

**Comment by yorikvanhavre** [comment]
Can you test if the problem still appears using a development version of FreeCAD from https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds ?

**Comment by Mannshoch** [comment]
I'm not anymore able to recreate the same environment. I have a new computer and meanwhile no access to this ifc files anymore.

I currently have freecad installed on Ubuntu from snapcraft beta (0.22-g93439591) from freecad-org and stable (2024-03-22-gda98001c) from realthunder on both a pip install ifcopenshell is requested by the Add-on and also works if I do that 
(running `freecad.pip install ifcopenshell` ).

I performed tests from a file I downloaded from https://github.com/RWTH-E3D/DigitalHub/blob/master/Version_2/DigitalHub_FM-HZG_v2.ifc

With 5GB RAM both FreeCAD Crash without any error message while importing.

```
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36458 (Git) Snap 958
Build type: Release
Branch: main
Hash: 934395913a6f9298f7b56bfe3b58c163f7011186
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Locale: German/Germany (de_DE)
Installed mods: 
  * dodo 1.0.1
  * FreeCAD-NativeIFC 2023.10.27
  * Nodes 0.1.36
  * ose-piping
  * InventorLoader 1.4.0
  * Render 2024.1.23
  * sheetmetal 0.4.6
```

**Comment by yorikvanhavre** [comment]
I can't recreate the problem, for me the file loads normally:
![image](https://github.com/yorikvanhavre/FreeCAD-NativeIFC/assets/1136856/fc59eefa-32cb-4855-a739-f646c8c13371)
Any backtrace if you launch FreeCAD from a terminal?

**Comment by Mannshoch** [comment]
FreeCad.log 

```
Msg: FreeCAD 0.22.0, Libs: 0.22.0devR36683 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2024
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.


Log: Time = 2024-Apr-04 16:00:58
Log: AboutImage = freecadabout
Log: AppDataSkipVendor = true
Log: AppHomePath = /snap/freecad/972/usr/
Log: AppIcon = freecad
Log: AppTempPath = /home/m/snap/freecad/common/temp/
Log: BOOST_VERSION = 1_74
Log: BinPath = /snap/freecad/972/usr/bin/
Log: BuildRepositoryURL = git://github.com/FreeCAD/FreeCAD.git main
Log: BuildRevision = 36683 (Git)
Log: BuildRevisionBranch = main
Log: BuildRevisionDate = 2024/03/30 16:46:25
Log: BuildRevisionHash = 6fbd8916ab4ae045fdaa4e16a3e44d7393b13e80
Log: BuildVersionMajor = 0
Log: BuildVersionMinor = 22
Log: BuildVersionPoint = 0
Log: BuildVersionSuffix = dev
Log: Console = 0
Log: CopyrightInfo = © Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2024
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.


Log: Debug = 0
Log: DocPath = /snap/freecad/972/usr/doc/
Log: EIGEN_VERSION = 3.4.0
Log: ExeName = FreeCAD
Log: ExeVendor = FreeCAD
Log: ExeVersion = 0.22.0
Log: LoggingConsole = 1
Log: LoggingFile = 1
Log: LoggingFileName = /home/m/snap/freecad/common/FreeCAD.log
Log: MaintainerUrl = https://www.freecad.org/wiki/Main_Page
Log: OCC_VERSION = 7.7.1
Log: PATH = /snap/freecad/972/usr/sbin:/snap/freecad/972/usr/bin:/snap/freecad/972/sbin:/snap/freecad/972/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/freecad/972/kf5/usr/bin
Log: PYSIDE_VERSION = 5.15.11
Log: PYTHONPATH = 
Log: PYTHON_VERSION = 3.10.12
Log: PythonSearchPath = /snap/freecad/972/usr/lib/python310.zip:/snap/freecad/972/usr/lib/python3.10:/snap/freecad/972/usr/lib/python3.10/lib-dynload
Log: QT_VERSION = 5.15.10
Log: RunMode = Gui
Log: SMESH_VERSION = 7.7.1.0
Log: SplashAlignment = Bottom|Left
Log: SplashInfoColor = #8aadf4
Log: SplashInfoPosition = 6,75
Log: SplashScreen = freecadsplash
Log: SplashTextColor = #8aadf4
Log: StartWorkbench = StartWorkbench
Log: SystemParameter = /home/m/snap/freecad/common/system.cfg
Log: UserAppData = /home/m/snap/freecad/common/
Log: UserCachePath = /home/m/snap/freecad/common/temp/
Log: UserConfigPath = /home/m/snap/freecad/common/
Log: UserHomePath = /home/m/snap/freecad/common
Log: UserMacroPath = /home/m/snap/freecad/common/
Log: UserParameter = /home/m/snap/freecad/common/user.cfg
Log: Verbose = 
Log: XERCESC_VERSION = 3.2.3
Log: Create Application
Log: Run App init script
Log: Init: starting App::FreeCADInit.py
Log: Init:   Searching for modules...
Log: Init:      Initializing /snap/freecad/972/usr/Mod/AddonManager... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Arch... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Assembly... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/CAM... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Draft... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Fem... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Help(Init.py not found)... ignore
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Idf... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Import... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Inspection... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Material... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Measure... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Mesh... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/MeshPart... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/OpenSCAD... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Part... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/PartDesign... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Plot(Init.py not found)... ignore
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Points... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/ReverseEngineering... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Robot... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Show(Init.py not found)... ignore
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Sketcher... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/SnapSetup... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Spreadsheet... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Start... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Surface... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/TechDraw... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Test... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Tux(Init.py not found)... ignore
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Web... done
Log: Init:      Initializing /home/m/snap/freecad/common/Mod/dodo/./... done
Log: Init:      Initializing /home/m/snap/freecad/common/Mod/FreeCAD-NativeIFC/./... done
Log: Init:      Initializing /home/m/snap/freecad/common/Mod/Nodes/./(Init.py not found)... ignore
Log: Init:      Initializing /home/m/snap/freecad/common/Mod/ose-piping(Init.py not found)... ignore
Log: Init:      Initializing /home/m/snap/freecad/common/Mod/InventorLoader/./... done
Log: Init:      Initializing /home/m/snap/freecad/common/Mod/Render/./(Init.py not found)... ignore
Log: Init:      Initializing /home/m/snap/freecad/common/Mod/sheetmetal/./... done
Log: Using /snap/freecad/972/usr/Mod as module path!
Log: System path after init:
Log:    /snap/freecad/972/usr/bin
Log:    /snap/freecad/972/usr/Mod/AddonManager
Log:    /snap/freecad/972/usr/Mod/Arch
Log:    /snap/freecad/972/usr/Mod/Assembly
Log:    /snap/freecad/972/usr/Mod/CAM
Log:    /snap/freecad/972/usr/Mod/Draft
Log:    /snap/freecad/972/usr/Mod/Fem
Log:    /snap/freecad/972/usr/Mod/Help
Log:    /snap/freecad/972/usr/Mod/Idf
Log:    /snap/freecad/972/usr/Mod/Import
Log:    /snap/freecad/972/usr/Mod/Inspection
Log:    /snap/freecad/972/usr/Mod/Material
Log:    /snap/freecad/972/usr/Mod/Measure
Log:    /snap/freecad/972/usr/Mod/Mesh
Log:    /snap/freecad/972/usr/Mod/MeshPart
Log:    /snap/freecad/972/usr/Mod/OpenSCAD
Log:    /snap/freecad/972/usr/Mod/Part
Log:    /snap/freecad/972/usr/Mod/PartDesign
Log:    /snap/freecad/972/usr/Mod/Plot
Log:    /snap/freecad/972/usr/Mod/Points
Log:    /snap/freecad/972/usr/Mod/ReverseEngineering
Log:    /snap/freecad/972/usr/Mod/Robot
Log:    /snap/freecad/972/usr/Mod/Show
Log:    /snap/freecad/972/usr/Mod/Sketcher
Log:    /snap/freecad/972/usr/Mod/SnapSetup
Log:    /snap/freecad/972/usr/Mod/Spreadsheet
Log:    /snap/freecad/972/usr/Mod/Start
Log:    /snap/freecad/972/usr/Mod/Surface
Log:    /snap/freecad/972/usr/Mod/TechDraw
Log:    /snap/freecad/972/usr/Mod/Test
Log:    /snap/freecad/972/usr/Mod/Tux
Log:    /snap/freecad/972/usr/Mod/Web
Log:    /home/m/snap/freecad/common/Mod/dodo
Log:    /home/m/snap/freecad/common/Mod/dodo/./
Log:    /home/m/snap/freecad/common/Mod/FreeCAD-NativeIFC
Log:    /home/m/snap/freecad/common/Mod/FreeCAD-NativeIFC/./
Log:    /home/m/snap/freecad/common/Mod/Nodes
Log:    /home/m/snap/freecad/common/Mod/Nodes/./
Log:    /home/m/snap/freecad/common/Mod/ose-piping
Log:    /home/m/snap/freecad/common/Mod/InventorLoader
Log:    /home/m/snap/freecad/common/Mod/InventorLoader/./
Log:    /home/m/snap/freecad/common/Mod/Render
Log:    /home/m/snap/freecad/common/Mod/Render/./
Log:    /home/m/snap/freecad/common/Mod/sheetmetal
Log:    /home/m/snap/freecad/common/Mod/sheetmetal/./
Log:    /snap/freecad/972/usr/sbin
Log:    /snap/freecad/972/usr/bin
Log:    /snap/freecad/972/sbin
Log:    /snap/freecad/972/bin
Log:    /usr/local/sbin
Log:    /usr/local/bin
Log:    /usr/sbin
Log:    /usr/bin
Log:    /sbin
Log:    /bin
Log:    /usr/games
Log:    /usr/local/games
Log:    /snap/freecad/972/kf5/usr/bin
Log: Init: App::FreeCADInit.py done
Log: Init: Creating Gui::Application and QApplication
Wrn: Qt: Session management error: Could not open network socket
Log: Local server 'FreeCAD' started
Log: OpenGL version is: 3.3 (3.3 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1)
Log: Run Gui init script
Log: Init: Running FreeCADGuiInit.py start script...
Log: Init:   Searching modules...
Log: Init:      Initializing /snap/freecad/972/usr/Mod/AddonManager... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Arch... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Assembly... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/CAM... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Draft... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Fem... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Help... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Idf(InitGui.py not found)... ignore
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Import... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Inspection... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Material... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Measure(InitGui.py not found)... ignore
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Mesh... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/MeshPart... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/OpenSCAD... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Part... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/PartDesign... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Plot(InitGui.py not found)... ignore
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Points... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/ReverseEngineering... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Robot... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Show(InitGui.py not found)... ignore
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Sketcher... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/SnapSetup(InitGui.py not found)... ignore
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Spreadsheet... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Start... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Surface... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/TechDraw... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Test... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Tux... done
Log: Init:      Initializing /snap/freecad/972/usr/Mod/Web... done
Log: Module: Part
Log: Loading Part module... done
Msg: flagMsg: 
Msg: flag2Msg: 
Log: Init:      Initializing /home/m/snap/freecad/common/Mod/dodo/./... done
Log: Init:      Initializing /home/m/snap/freecad/common/Mod/FreeCAD-NativeIFC/./... done
Log: Init:      Initializing /home/m/snap/freecad/common/Mod/Nodes/./... done
Log: Failed to get handle to InitGui -- no icon                                can be generated,
 check classname in package.xml
Log: Init:      Initializing /home/m/snap/freecad/common/Mod/ose-piping... done
Log: Init:      Initializing /home/m/snap/freecad/common/Mod/InventorLoader/./... done
Log: Init:      Initializing /home/m/snap/freecad/common/Mod/Render/./... done
Log: Init:      Packaged workbench Render Workbench specified icon            in class RenderWorkbenchLog:  ... replacing with icon from package.xml data.
Log: Init:      Initializing /home/m/snap/freecad/common/Mod/sheetmetal/./... done
Log: All modules with GUIs using InitGui.py are now initialized
Log: All modules with GUIs initialized using pkgutil are now initialized
Log: Init: Loading FreeCAD GUI
Log: Init: Running FreeCADGuiInit.py start script... done
Log: Init: Activating default workbench StartWorkbench
Log: Loading GUI of Web module... done
Log: Loading GUI of Start module... done
Log: Loading Start module... done
Log: Sandboxing disabled by user.
Log: Init: Showing main window
Log: Main window restored
Log: Show main window
Log: Toolbars restored
Log: Couldn't connect to spacenav daemon. Please ignore if you don't have a spacemouse.
Log: Init: Entering event loop
Log: Init: Executing event loop...
Log: Init: Processing command line files
Log: Loading Mesh module... done
Err: No stream support: No module named 'lark'Err: 
Log: IFC: Created #173: IfcSite, 'DH Liegenschaft'
Log: Loading GUI of Part module... done
Log: IFC: Created #142: IfcBuilding, 'DigitalHub'
```



CLI

```

m@VMWareTest:~$ freecad -l
FreeCAD 0.22.0, Libs: 0.22.0devR36683 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2024
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.


Adding snap-specific PYTHONPATH to sys.path: /home/m/snap/freecad/common/.local/lib/python3.10/site-packages:/snap/freecad/972/lib/python3.10/site-packages:/snap/freecad/972/usr/lib/python3/dist-packages
Sheet Metal workbench loaded
Qt: Session management error: Could not open network socket
flag
flag2
connect failed: No such file or directory
No stream support: No module named 'lark'
Terminated

```

![htop](https://github.com/yorikvanhavre/FreeCAD-NativeIFC/assets/7795891/50a82526-03d9-4a9c-9aac-4d76367c2984)
